=== LaszAndrea/DJ7PNE_XMLGyak/DJ7PNE_1109/studentDJ7PNE.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="class">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="student" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="firstname" type="xs:string" />
                        <xs:element name="lastname" type="xs:string" />
                        <xs:element name="nickname" type="xs:string" />
                        <xs:element name="age" type="xs:int" />
                    </xs:all>
                    <xs:attribute name="id" type="xs:int" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
</xs:element>
</xs:schema>

=== LaszAndrea/DJ7PNE_XMLGyak/DJ7PNE_1109/studentDJ7PNE.xml
<?xml version="1.0" encoding="UTF-8"?>

<class xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="studentDJ7PNE.xsd">
    <student id="1">
        <firstname>László</firstname>
        <lastname>Andrea</lastname>
        <nickname>Andi</nickname>
        <age>21</age>
    </student>

    <student id="2">
        <firstname>Bogyó</firstname>
        <lastname>Hanna</lastname>
        <nickname>Hannus</nickname>
        <age>18</age>
    </student>

    <student id="3">
        <firstname>Kiss</firstname>
        <lastname>Péter</lastname>
        <nickname>Peti</nickname>
        <age>23</age>
    </student>
</class>

=== LaszAndrea/DJ7PNE_XMLGyak/DJ7PNE_1116/studentDJ7PNE.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type = "text/xsl" href = "student-for-each.xsl"?>

<class xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="studentDJ7PNE.xsd">
    <student id="1">
        <firstname>László</firstname>
        <lastname>Andrea</lastname>
        <nickname>Andi</nickname>
        <age>21</age>
        <osztondij>25500</osztondij>
    </student>

    <student id="2">
        <firstname>Bogyó</firstname>
        <lastname>Hanna</lastname>
        <nickname>Hannus</nickname>
        <age>18</age>
        <osztondij>13000</osztondij>
    </student>

    <student id="3">
        <firstname>Kiss</firstname>
        <lastname>Péter</lastname>
        <nickname>Peti</nickname>
        <age>23</age>
        <osztondij>18000</osztondij>
    </student>
</class>
